### ISSUE TITLE
Library License

### ISSUE THREAD

**Issue by Xorlev** [brunobrandes/fullcontact-api-csharp#1]
Hi @brunobrandes,

We're super excited that you've started to write a C# library for the FullContact Person API! Right on. We'd be happy to link it in our docs as well once you feel it's ready to be used by others (should you wish us to). However, you'll need to apply a license to the project before we could recommend it for use.

https://opensource.org/licenses

For example, .NET Core uses the MIT license, and it's also a license we use often in our own projects.

**Comment by brunobrandes** [comment]
Hello @Xorlev 
It's done

This software is open source, licensed under the MIT License (MIT). See https://github.com/brunobrandes/fullcontact-api-csharp/blob/master/LICENSE.md for details.

Hugs

**Comment by brunobrandes** [comment]
Hello @Xorlev 
It's done

This software is open source, licensed under the MIT License (MIT). See https://github.com/brunobrandes/fullcontact-api-csharp/blob/master/LICENSE.md for details.

Hugs
