### ISSUE TITLE
missing dependency SimpleInjector

### ISSUE THREAD

**Issue by tinohager** [brunobrandes/fullcontact-api-csharp#4]
the nuget file missing the dependency SimpleInjector

```
    <dependencies>
        <group targetFramework=".NETFramework4.6.1">
            <dependency id="Newtonsoft.Json" version="8.0.3" />
            <dependency id="SimpleInjector" version="3.1.5" />
        </group>
    </dependencies>
```

**Comment by brunobrandes** [comment]
@tinohager
This solution dosen't have SimpleInjector depedency.

In my examples I use SimpleInjector, but you can use your favorite [dependency injection framework](http://goo.gl/qsmRuk) 

Hugs
